[build]
  publish = "."

[[edge_functions]]
  path = "/*"
  function = "geo-cookie"

# Form handling
[forms]
  # Enable form processing
  enabled = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com; connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://region1.analytics.google.com https://www.googletagmanager.com; frame-ancestors 'none';"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for broken PDF links to contact page
[[redirects]]
  from = "/Rosehill_Security_-_Rapid_Defender_4pp_OCT2018.pdf"
  to = "/contact-us.html?product=rapid-defender"
  status = 301

[[redirects]]
  from = "/Rosehill_Security_-_Impakt_Defender_Layout_NOV2023.pdf"
  to = "/contact-us.html?product=impakt-defender"
  status = 301

[[redirects]]
  from = "/Rosehill_Security_-_Anti-Trespass_web_NOV2018.pdf"
  to = "/contact-us.html?product=anti-trespass"
  status = 301